// react/src/blocks/stat-cards.tsx
import { Card, CardContent } from "../components/card";
import { cn } from "../lib/cn";

export interface Stat {
  label: string;
  value: string;
  delta?: string;
}

export function StatCards({ stats }: { stats: Stat[] }) {
  return (
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      {stats.map((s) => (
        <Card key={s.label}>
          <CardContent className="p-6">
            <p className="font-mono text-xs uppercase tracking-wide text-muted-foreground">{s.label}</p>
            <p className="mt-2 font-display text-3xl font-bold tracking-tight">{s.value}</p>
            {s.delta && (
              <p
                className={cn(
                  "mt-1 text-xs font-bold",
                  s.delta.startsWith("-") ? "text-rose-500" : "text-success",
                )}
              >
                {s.delta}
              </p>
            )}
          </CardContent>
        </Card>
      ))}
    </div>
  );
}

// vue/src/blocks/StatCards.vue
<script setup lang="ts">
import Card from "../components/Card.vue";
import CardContent from "../components/CardContent.vue";

defineProps<{ stats: { label: string; value: string; delta?: string }[] }>();
</script>

<template>
  <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
    <Card v-for="s in stats" :key="s.label">
      <CardContent class="p-6">
        <p class="font-mono text-xs uppercase tracking-wide text-muted-foreground">{{ s.label }}</p>
        <p class="mt-2 font-display text-3xl font-bold tracking-tight">{{ s.value }}</p>
        <p
          v-if="s.delta"
          class="mt-1 text-xs font-bold"
          :class="s.delta.startsWith('-') ? 'text-rose-500' : 'text-success'"
        >
          {{ s.delta }}
        </p>
      </CardContent>
    </Card>
  </div>
</template>
