// vue/src/components/Marquee.vue
<script setup lang="ts">
import { computed } from "vue";
const props = defineProps<{ items: string[] }>();
const row = computed(() => [...props.items, ...props.items]);
</script>

<template>
  <div class="overflow-hidden border-y-2 border-foreground bg-foreground py-3 text-background">
    <div class="spark-marquee-track flex w-max items-center gap-8 whitespace-nowrap">
      <span
        v-for="(item, i) in row"
        :key="i"
        class="flex items-center gap-8 font-mono text-sm font-medium uppercase tracking-widest"
      >
        {{ item }}
        <span class="text-primary">✦</span>
      </span>
    </div>
  </div>
</template>

// react/src/components/marquee.tsx
/** Infinite scrolling ticker. Reverses automatically in RTL. */
export function Marquee({ items }: { items: readonly string[] }) {
  const row = [...items, ...items];
  return (
    <div className="overflow-hidden border-y-2 border-foreground bg-foreground py-3 text-background">
      <div className="spark-marquee-track flex w-max items-center gap-8 whitespace-nowrap">
        {row.map((item, i) => (
          <span key={i} className="flex items-center gap-8 font-mono text-sm font-medium uppercase tracking-widest">
            {item}
            <span className="text-primary">✦</span>
          </span>
        ))}
      </div>
    </div>
  );
}
